/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/payer/payments/{payerPageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetPayerPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payer/payments/{payerPageId}/currency-selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SelectPayerPaymentCurrency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAdminCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAdminPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/payments/{paymentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAdminPayment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/payments/{paymentId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SettleAdminPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/reorg-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAdminReorgAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/observation-health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAdminObservationHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAdminAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-log/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAdminAuditLogEntry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhook-deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAdminWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/integration-api-credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAdminIntegrationApiCredentials"];
        put?: never;
        post: operations["CreateAdminIntegrationApiCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/integration-api-credentials/{credentialId}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RotateAdminIntegrationApiCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/integration-api-credentials/{credentialId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DisableAdminIntegrationApiCredential"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhook-endpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListAdminWebhookEndpoints"];
        put?: never;
        post: operations["CreateAdminWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhook-endpoints/{endpointId}/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UpdateAdminWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhook-endpoints/{endpointId}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RotateAdminWebhookEndpointSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhook-endpoints/{endpointId}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DisableAdminWebhookEndpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/native-eth-address-pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetAdminNativeEthAddressPool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/native-eth-address-pool/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ImportAdminNativeEthAddressPool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-log/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ExportAdminAuditLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/webhook-deliveries/{eventId}/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ResendAdminWebhookDelivery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StartAdminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/mfa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["CompleteAdminMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/step-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["StepUpAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["GenerateAdminRecoveryCodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LogoutAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AdminAuditLogEntryDetailReadModel: {
            /** Format: uuid */
            eventId: string;
            /** Format: date-time */
            occurredAt: string;
            eventType: string;
            outcome: string;
            actorType: string;
            actorId: string;
            sourceService: string;
            sourceIp: null | string;
            userAgent: null | string;
            correlationId: string;
            reasonCode: string;
            subjectType: string;
            subjectId: string;
        };
        AdminAuditLogEntryReadModel: {
            /** Format: uuid */
            eventId: string;
            /** Format: date-time */
            occurredAt: string;
            eventType: string;
            outcome: string;
            actorType: string;
            actorId: string;
            reasonCode: string;
            subjectType: string;
            subjectId: string;
        };
        AdminAuditLogExportHttpRequest: {
            /** Format: int32 */
            limit: null | number | string;
        };
        AdminAuditLogExportHttpResponse: {
            /** Format: date-time */
            exportedAt: string;
            entries: components["schemas"]["AdminAuditLogEntryDetailReadModel"][];
        };
        AdminAuditLogHttpResponse: {
            entries: components["schemas"]["AdminAuditLogEntryReadModel"][];
        };
        AdminCsrfHttpResponse: {
            csrfToken: string;
        };
        AdminIntegrationApiCredentialCreateHttpRequest: {
            name: null | string;
        };
        AdminIntegrationApiCredentialHttpResponse: {
            credential: components["schemas"]["AdminIntegrationApiCredentialReadModel"];
        };
        AdminIntegrationApiCredentialMutationHttpRequest: {
            /** Format: int64 */
            expectedVersion: null | number | string;
        };
        AdminIntegrationApiCredentialReadModel: {
            /** Format: uuid */
            id: string;
            name: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: null | string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number | string;
        };
        AdminIntegrationApiCredentialSecretHttpResponse: {
            credential: components["schemas"]["AdminIntegrationApiCredentialReadModel"];
            token: string;
        };
        AdminIntegrationApiCredentialsHttpResponse: {
            credentials: components["schemas"]["AdminIntegrationApiCredentialReadModel"][];
        };
        AdminLoginStartHttpRequest: {
            username: null | string;
            password: null | string;
        };
        AdminLoginStartHttpResponse: {
            status: string;
            /** Format: uuid */
            challengeId: null | string;
        };
        AdminLogoutHttpResponse: {
            status: string;
        };
        AdminMfaCompleteHttpRequest: {
            /** Format: uuid */
            challengeId: null | string;
            totpCode: null | string;
            recoveryCode: null | string;
        };
        AdminMfaCompleteHttpResponse: {
            status: string;
        };
        AdminNativeEthAddressPoolImportHttpRequest: {
            addresses: null | string[];
        };
        AdminNativeEthAddressPoolImportHttpResponse: {
            /** Format: uuid */
            importId: string;
            /** Format: int32 */
            importedCount: number | string;
            summary: components["schemas"]["AdminNativeEthAddressPoolSummary"];
        };
        AdminNativeEthAddressPoolSummary: {
            /** Format: int32 */
            unusedCount: number | string;
            /** Format: int32 */
            assignedCount: number | string;
            /** Format: int32 */
            retiredCount: number | string;
            /** Format: int32 */
            lowCapacityThreshold: number | string;
            isLowCapacity: boolean;
        };
        AdminObservationHealthHttpResponse: {
            currencies: components["schemas"]["ObservationHealthReadModel"][];
        };
        AdminPaymentDetailReadModel: {
            /** Format: uuid */
            paymentId: string;
            externalReference: string;
            fiatCurrency: string;
            /** Format: int64 */
            fiatAmountMinor: number | string;
            status: string;
            payerPageId: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            lateAcceptanceEndsAt: string;
            selectedCurrency: null | string;
            expectedCryptoAmount: null | string;
            paymentAddress: null | string;
            observedTotal: null | string;
            confirmedEligibleTotal: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            settledAt: null | string;
            /** Format: int64 */
            version: number | string;
        };
        AdminPaymentSettlementHttpRequest: {
            /** Format: int64 */
            expectedVersion: null | number | string;
            reason: null | string;
        };
        AdminPaymentsHttpResponse: {
            payments: components["schemas"]["AdminPaymentSummaryReadModel"][];
        };
        AdminPaymentSummaryReadModel: {
            /** Format: uuid */
            paymentId: string;
            externalReference: string;
            fiatCurrency: string;
            /** Format: int64 */
            fiatAmountMinor: number | string;
            status: string;
            selectedCurrency: null | string;
            expectedCryptoAmount: null | string;
            paymentAddress: null | string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        AdminRecoveryCodesHttpResponse: {
            /** Format: date-time */
            generatedAt: string;
            recoveryCodes: string[];
        };
        AdminReorgAlertReadModel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            paymentId: string;
            supportedCurrency: string;
            transactionHash: string;
            /** Format: int32 */
            previousConfirmations: number | string;
            /** Format: int32 */
            newConfirmations: number | string;
            previousBlockHash: null | string;
            newBlockHash: null | string;
            /** Format: int64 */
            previousBlockHeight: null | number | string;
            /** Format: int64 */
            newBlockHeight: null | number | string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number | string;
        };
        AdminReorgAlertsHttpResponse: {
            alerts: components["schemas"]["AdminReorgAlertReadModel"][];
        };
        AdminSessionHttpResponse: {
            status: string;
            /** Format: uuid */
            adminAccountId: string;
            username: string;
            /** Format: date-time */
            mfaAuthenticatedAt: string;
            /** Format: date-time */
            stepUpAuthenticatedAt: string;
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            idleExpiresAt: string;
        };
        AdminStepUpHttpRequest: {
            totpCode: null | string;
        };
        AdminStepUpHttpResponse: {
            status: string;
            /** Format: date-time */
            stepUpAuthenticatedAt: string;
            /** Format: date-time */
            idleExpiresAt: string;
        };
        AdminWebhookDeliveriesHttpResponse: {
            deliveries: components["schemas"]["AdminWebhookDeliveryReadModel"][];
        };
        AdminWebhookDeliveryReadModel: {
            /** Format: uuid */
            webhookEventId: string;
            /** Format: uuid */
            paymentId: string;
            paymentExternalReference: string;
            eventType: string;
            eventVersion: string;
            status: string;
            /** Format: int32 */
            attemptCount: number | string;
            lastErrorCode: null | string;
            /** Format: date-time */
            nextAttemptAt: null | string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastAttemptedAt: null | string;
            lastAttemptResult: null | string;
            /** Format: int32 */
            lastHttpStatusCode: null | number | string;
            lastSafeErrorCode: null | string;
            correlationId: string;
        };
        AdminWebhookDeliveryResendHttpResponse: {
            status: string;
            deliveryStatus: string;
        };
        AdminWebhookEndpointCreateHttpRequest: {
            /** Format: uuid */
            integrationApiCredentialId: null | string;
            url: null | string;
            secretReference: null | string;
            eventTypes: null | string[];
        };
        AdminWebhookEndpointHttpResponse: {
            endpoint: components["schemas"]["AdminWebhookEndpointReadModel"];
        };
        AdminWebhookEndpointReadModel: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            integrationApiCredentialId: string;
            url: string;
            secretReference: string;
            status: string;
            eventTypes: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: int64 */
            version: number | string;
        };
        AdminWebhookEndpointSecretRotationHttpRequest: {
            /** Format: int64 */
            expectedVersion: null | number | string;
            secretReference: null | string;
        };
        AdminWebhookEndpointsHttpResponse: {
            endpoints: components["schemas"]["AdminWebhookEndpointReadModel"][];
        };
        AdminWebhookEndpointUpdateHttpRequest: {
            /** Format: int64 */
            expectedVersion: null | number | string;
            url: null | string;
            eventTypes: null | string[];
        };
        IntegrationApiProblemResponse: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            code: null | string;
            correlationId: null | string;
            errors?: null | {
                [key: string]: string[];
            };
        };
        ObservationHealthReadModel: {
            supportedCurrency: string;
            providerName: string;
            status: string;
            /** Format: date-time */
            lastSuccessfulAt: null | string;
            /** Format: date-time */
            lastFailedAt: null | string;
            lastSafeErrorCode: null | string;
        };
        PaymentOptionResponse: {
            supportedCurrency: string;
            status: string;
            unavailableReasonCode: null | string;
        };
        PaymentResponse: {
            /** Format: uuid */
            paymentId: string;
            status: string;
            payerPageUrl: string;
            /** Format: date-time */
            expiresAt: string;
            fiatCurrency: string;
            /** Format: int64 */
            fiatAmountMinor: number | string;
            externalReference: string;
            selectedCurrency: null | string;
            expectedCryptoAmount: null | string;
            paymentAddress: null | string;
            observedTotal: null | string;
            /** Format: date-time */
            completedAt: null | string;
            /** Format: date-time */
            settledAt: null | string;
            returnUrl: null | string;
            paymentOptions: components["schemas"]["PaymentOptionResponse"][];
        };
        SelectPayerPaymentCurrencyHttpRequest: {
            supportedCurrency: null | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetPayerPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payerPageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    SelectPayerPaymentCurrency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payerPageId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["SelectPayerPaymentCurrencyHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    GetAdminCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCsrfHttpResponse"];
                };
            };
        };
    };
    GetAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSessionHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ListAdminPayments: {
        parameters: {
            query?: {
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentsHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    GetAdminPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentDetailReadModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    SettleAdminPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminPaymentSettlementHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentDetailReadModel"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ListAdminReorgAlerts: {
        parameters: {
            query?: {
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminReorgAlertsHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    GetAdminObservationHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminObservationHealthHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ListAdminAuditLog: {
        parameters: {
            query?: {
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditLogHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    GetAdminAuditLogEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditLogEntryDetailReadModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ListAdminWebhookDeliveries: {
        parameters: {
            query?: {
                limit?: number | string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebhookDeliveriesHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ListAdminIntegrationApiCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIntegrationApiCredentialsHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    CreateAdminIntegrationApiCredential: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminIntegrationApiCredentialCreateHttpRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIntegrationApiCredentialSecretHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    RotateAdminIntegrationApiCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminIntegrationApiCredentialMutationHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIntegrationApiCredentialSecretHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    DisableAdminIntegrationApiCredential: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                credentialId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminIntegrationApiCredentialMutationHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminIntegrationApiCredentialHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ListAdminWebhookEndpoints: {
        parameters: {
            query?: {
                integrationApiCredentialId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebhookEndpointsHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    CreateAdminWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminWebhookEndpointCreateHttpRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebhookEndpointHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    UpdateAdminWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminWebhookEndpointUpdateHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebhookEndpointHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    RotateAdminWebhookEndpointSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminWebhookEndpointSecretRotationHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebhookEndpointHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    DisableAdminWebhookEndpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                endpointId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminIntegrationApiCredentialMutationHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebhookEndpointHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    GetAdminNativeEthAddressPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNativeEthAddressPoolSummary"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ImportAdminNativeEthAddressPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminNativeEthAddressPoolImportHttpRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminNativeEthAddressPoolImportHttpResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ExportAdminAuditLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminAuditLogExportHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminAuditLogExportHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    ResendAdminWebhookDelivery: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eventId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminWebhookDeliveryResendHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    StartAdminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminLoginStartHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLoginStartHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    CompleteAdminMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminMfaCompleteHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminMfaCompleteHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    StepUpAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["AdminStepUpHttpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStepUpHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    GenerateAdminRecoveryCodes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRecoveryCodesHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
            /** @description Too Many Requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
    LogoutAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLogoutHttpResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntegrationApiProblemResponse"];
                };
            };
        };
    };
}
